<a href="https://colab.research.google.com/github/Adeel-abbasi/DS-A/blob/main/LAB_4_20sw018.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab 4
Section 2
Roll no 20sw018

Task 1

In [1]:


import numpy as np

#using the range function to generate the even numbers
e_num = np.arange(2, 34, 2)

X = e_num.reshape(4, 4)

print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task 2

In [2]:


import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers
Y = X[X % 2 != 0]

#printing the origenal array
print("Original array X:\n", X)

#printing the odd numbers
print("\nArray Y with odd numbers:\n", Y)

Original array X:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with odd numbers:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task 3

In [3]:


import numpy as np

# Creating a 4 x 4 ndarray with columns of consecutive numbers
X = np.arange(1, 5)

# Using broadcasting to create the desired array
X = X[:, np.newaxis] * np.ones((1, 4), dtype=int)

#printing the array
print(X)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
